### ISSUE TITLE
Invasive vs non-invasive

### ISSUE THREAD

**Issue by fxstr** [infect-org/frontend#100]
«Ich werde ein zusätzliches Feld für invasiv (z.B. Blutkulturen) vs. non-invasiv (z.B. Wundabstriche, Urine) liefern, wobei man nach diesem Feld selektionieren können muss»

@pascalmfrey What's your take on this?

**Comment by pascalmfrey** [comment]
This should be a data/population filter. Depending on the data we actually get, we could also discuss adding more granularity by giving the option to filter by each sample site; the general dichotomisation of invasive/non-invasive is fine too and might be easier to implement as a first step.
