### ISSUE TITLE
Matrix: Hover over "Beta-lactam + inhibitor"

### ISSUE THREAD

**Issue by sandrokneubuehl** [infect-org/frontend#113]
![screen shot 2018-03-13 at 18 46 56](https://user-images.githubusercontent.com/29794950/37359919-1f938b80-26ef-11e8-8120-1e94a10d6c44.png)

**Comment by fxstr** [comment]
@eventEmitter Needs to move the substance class «Beta-lactam + inhibitor» up in the substance class data master list. The position in this google spreadsheet determines the `z-index`. Magic.

**Comment by fxstr** [comment]
![image](https://user-images.githubusercontent.com/1211144/42966915-e4d0181e-8b9e-11e8-8c49-bf1d72bb26f3.png)
