### ISSUE TITLE
UI: intro.js tooltip

### ISSUE THREAD

**Issue by sandrokneubuehl** [infect-org/frontend#114]
- [ ] move close-button to top-right / remove "button-style"
- [ ] adapt this hint tooltip on small screens:
![screen shot 2018-03-13 at 18 50 58](https://user-images.githubusercontent.com/29794950/37360119-9d655bc4-26ef-11e8-92cb-997a88ef7acb.png)

**Comment by fxstr** [comment]
Fixed with recent release that replaces hints with guided tour.
