### ISSUE TITLE
Create under construction page

### ISSUE THREAD

**Issue by fxstr** [infect-org/frontend#19]

**Comment by fxstr** [comment]
**Coming Mid-November 2017**,
you will find the all-new INFECT 2.0 in this place.

**Comment by fxstr** [comment]
@sandrokneubuehl This needs to be a static site outside of the infect app as we must publish it on infect.info without publishing the new app.

**Comment by sandrokneubuehl** [comment]
we will use the matrix and put the letters of the phrase as green schnittpunkt-bubbles

**Comment by sandrokneubuehl** [comment]
done
![screen shot 2017-10-25 at 17 24 52](https://user-images.githubusercontent.com/29794950/32007297-73715bdc-b9a9-11e7-9467-daaebdb65bae.png)
