### ISSUE TITLE
Make sure matrix can be scrolled

### ISSUE THREAD

**Issue by fxstr** [infect-org/frontend#21]
Especially horizontally (for small screens)

**Comment by sandrokneubuehl** [comment]
added scrolling-x.
@fxstr maybe you should add a padding on the right side of your matrix svg. like you did on the left. look at this:
![screen shot 2017-10-17 at 12 15 18](https://user-images.githubusercontent.com/29794950/31659939-0d8b18fe-b336-11e7-92b1-9bed25da3ddf.png)

**Comment by sandrokneubuehl** [comment]
nevermind... i fixed it.

**Comment by sandrokneubuehl** [comment]
done.
