### ISSUE TITLE
improve filter list

### ISSUE THREAD

**Issue by fxstr** [infect-org/frontend#32]
- [x] Add styles for radio inputs
    ![image](https://user-images.githubusercontent.com/1211144/31774029-d83d1a98-b4e4-11e7-99aa-8b6895fbc330.png)
- [x] Indent second line of multi line label
    ![image](https://user-images.githubusercontent.com/1211144/31774054-e99456da-b4e4-11e7-9a58-908546b95694.png)
- [x] Add space at bottom
    ![image](https://user-images.githubusercontent.com/1211144/31774156-352b5db4-b4e5-11e7-9aea-4b6194502a53.png)
- Perfect proportions of tabs and search input
![image](https://user-images.githubusercontent.com/1211144/31774183-4ecde606-b4e5-11e7-9fbe-eb75e7b415da.png)
- Remove diagnosis tab

**Comment by sandrokneubuehl** [comment]
add margin to last group element to optimise scrolling

**Comment by sandrokneubuehl** [comment]
to set the padding-bottom exactly, we probably use js. or we assume the height of the regions group.
