### ISSUE TITLE
add, then style error messages

### ISSUE THREAD

**Issue by fxstr** [infect-org/frontend#35]

**Comment by sandrokneubuehl** [comment]
added a error notification.

to toggle it: 
select **.notification-container**
add/remove class **.notification-container--active**

add the error text here: 
 <div class="notification-container">
            <div class="notification__error-icon">
                <a class="notification__link" onclick="document.querySelector('.notification-container').classList.remove('notification-container--active')">
                    <img src="/img/error.svg" />
                </a>
            </div>
            <div class="notification__message message">
                <h2>UPS, something went wrong!</h2>
                **<p>Hi Felix! Your text will come here</p>**
            </div>
        </div>
