### ISSUE TITLE
typo error: region -> ticion

### ISSUE THREAD

**Issue by sandrokneubuehl** [infect-org/frontend#41]
<img width="185" alt="screen shot 2017-10-25 at 20 45 43" src="https://user-images.githubusercontent.com/29794950/32016951-87be28d8-b9c5-11e7-8e3d-22a588bef662.png">

**Comment by fxstr** [comment]
Replaced by real values:
![image](https://user-images.githubusercontent.com/1211144/32054927-6b6d177a-ba60-11e7-882e-dfe352b559dd.png)
