### ISSUE TITLE
improve search

### ISSUE THREAD

**Issue by fxstr** [infect-org/frontend#43]
- [ ] font size (placeholder/input) smaller in input
- clear button: to the right of the input as a &times; symbol (this prevents the layout from changing when enterding text)

![image](https://user-images.githubusercontent.com/1211144/32018263-a291df66-b9c9-11e7-8a45-6d2f80a9fd0f.png)

**Comment by sandrokneubuehl** [comment]
der IE macht das automatisch mit dem X am Ende, scheint mir?

**Comment by sandrokneubuehl** [comment]
fontsize hab ich angepasst

**Comment by fabianjordi** [comment]
…ohne Details zu kennen: nutzt <input type="search" .. /> (und nicht type="text") und setzt die "appearance" auf "none;". Dabei bitte Vendor-Prefixes nutzen.
