### ISSUE TITLE
Display size of the dots should be computed not lienar

### ISSUE THREAD

**Issue by eventEmitter** [infect-org/frontend#45]
it seems that that dot size is computed linear, this is probably not very helpful. it should either be
- computed logarithmically
- or with an upper bound

@pascalmfrey what do you think?

**Comment by pascalmfrey** [comment]
Considering that we would primarily like to make it easier to identify data points with a low sample size, I think it might be best to use both, Log and upper limit: how about we make the tile site variable for log(N) = 0 to 3, as a sample size of 1000 is reasonably large to give us an appropriate accuracy of resistance % ?

**Comment by eventEmitter** [comment]
log & cutoff at 1'000 should be fine

**Comment by fxstr** [comment]
Implementation:
- Use min(sampleSize, 1000) for max radius; all sampleSizes > 1000 have the same radius.
- Use log10 to calculate radius. Assuming all circles have a radius between 10 and 30 px:
    - sampleSize 1 -> radius 10
    - sampleSize 10 -> radius 16.6
    - sampleSize 100 -> radius 23.3
    - sampleSize 1000 -> radius 30
How does that sound & look, @eventEmitter @pascalmfrey ?

**Comment by eventEmitter** [comment]
@pascalmfrey: splendid!!
