### ISSUE TITLE
Style the scrollbar in the filter section

### ISSUE THREAD

**Issue by eventEmitter** [infect-org/frontend#46]
it looks not exactly beautiful on non apple systems
![image](https://user-images.githubusercontent.com/603475/32047923-d409f3b6-ba47-11e7-8768-dbd4b714dd77.png)

**Comment by sandrokneubuehl** [comment]
to be done: test in IE and non-apple systems, if styles are applied or not.

**Comment by eventEmitter** [comment]
looks nice on chrome/linux!

![image](https://user-images.githubusercontent.com/603475/32341781-c5c8692e-bffe-11e7-8c8e-922c7a59dca8.png)
