### ISSUE TITLE
let the user exit the info overlay with the esc key

### ISSUE THREAD

**Issue by linaGirl** [infect-org/frontend#47]
extremely high priority :dancing_men:

**Comment by lkappeler** [comment]
may display an 'x' instead of the 'i' when the dialog is open since it's not intuitive (at least for me) the info button is a toggle button and closes the overlay when clicked again

**Comment by fxstr** [comment]
«i» now beomes an «x» when overlay is open:
![image](https://user-images.githubusercontent.com/1211144/36858518-aa7cb316-1d7b-11e8-8b4e-913a385161c9.png)

👊
