### ISSUE TITLE
Neue Texte About einpflegen

### ISSUE THREAD

**Issue by fxstr** [infect-org/frontend#55]

**Comment by sandrokneubuehl** [comment]
wo finde ich die texte?

**Comment by fxstr** [comment]
Hier, sind aber noch nicht definitiv. 
https://docs.google.com/document/d/1K52I-OMx6dOxG48z7S0tkrJGrnwxdpgcZt5wSsE7VYs/edit#heading=h.7zzokm8g1rbd
