### ISSUE TITLE
it's possible to select more than one "population"

### ISSUE THREAD

**Issue by sandrokneubuehl** [infect-org/frontend#58]
![screen shot 2017-10-31 at 15 39 10](https://user-images.githubusercontent.com/29794950/32229741-d6522130-be51-11e7-8197-5369066cdc73.png)

1. select population via. radio button ie. geneva
2. select another population via radio buttons ie. north east
3. select "geneva" via favorites fitlers

**Comment by fxstr** [comment]
![image](https://user-images.githubusercontent.com/1211144/32366792-0a4b7524-c080-11e7-9395-80db0fa76893.png)
