### ISSUE TITLE
matrix header overlaps scrollbar

### ISSUE THREAD

**Issue by sandrokneubuehl** [infect-org/frontend#59]
![screen shot 2017-10-31 at 16 27 59](https://user-images.githubusercontent.com/29794950/32232511-7bff6bdc-be58-11e7-9fb6-9c60b7df7e60.png)

**Comment by sandrokneubuehl** [comment]
let's try this solution:
https://codepen.io/anon/pen/qVdVqa

**Comment by fxstr** [comment]
@sandrokneubuehl Sinnvollerweise fixieren wir dabei – falls das geht – auch die Labels der Bakterien
