### ISSUE TITLE
Add «beta» to logo

### ISSUE THREAD

**Issue by eventEmitter** [infect-org/frontend#64]

**Comment by fxstr** [comment]
Text: «INFECT is in a beta stage. It may contain bugs – if you find any, please contact felix@joinbox.com. The data displayed has not yet been validated. Please direct any content related questions to pascal.frey@insel.ch. More information»

**Comment by fxstr** [comment]
Implemented: 
![image](https://user-images.githubusercontent.com/1211144/32339988-a24fbc5e-bff9-11e7-881d-e5f7805e3835.png)

@sandrokneubuehl Please style (see http://infect.info and let's discuss details in person)

**Comment by pascalmfrey** [comment]
Looks fine! I hope to be able to use pascal@infect.info by that time (and you felix@infect.info?)

Typo: There's a space missing between contact and felix@..
