### ISSUE TITLE
Invert the color values for the red dots

### ISSUE THREAD

**Issue by eventEmitter** [infect-org/frontend#67]
the dots representing the highest resistance should have the most intense red value

**Comment by fxstr** [comment]
@myself not so fast. create variants first, let ifik decide

**Comment by fxstr** [comment]
Mail Felix:
> Anbei sende ich Ihnen auch die verschiedenen Varianten für die Farbgebung zu (die Beschreibung finden Sie jeweils im Dateinamen). Wir haben diese intern vorbesprochen und schlagen vor: 
- Die heutige Farbgebung (grün intensiv, rot schwach) zu belassen. Optisch ist die Unterscheidung so viel klarer als bei der umgekehrten (rot intensiv, grün schwach) oder gleichbleibenden (alle gleich intensiv) Farbgebung. 

Antwort A. Kronenberg:
> Bezüglich Farbgebung bin ich mit Ihnen einig.
