### ISSUE TITLE
Create new substanceClass «Penicillin + Inhibitors»

### ISSUE THREAD

**Issue by eventEmitter** [infect-org/frontend#69]
add compounds:
- Amoxi / Clavu
- Pip / Taz

@pascalmfrey please review

**Comment by fxstr** [comment]
Sort order:
- sensitive
- dann stable
- dann «Pencillins plus Inhibitors»

**Comment by eventEmitter** [comment]
**not** approved by @pascalmfrey 

- Amoxi / Clavu: add to Penicillinase-sensitive penicillin
- Pip / Taz: ureidopenicillin
