### ISSUE TITLE
update sort order of substance classes

### ISSUE THREAD

**Issue by fxstr** [infect-org/frontend#72]
Bis Chinolone belassen, dann
Aminoglycoside
Makrolide
Lincos
Glycopeptide
Oxas
Tetracycline
Folsäuren
Folat Inhibitoren
Rest alphabetisch nach Substanzklasse

**Comment by fxstr** [comment]
Betrifft
- substanceClasses.json
- Data Master

**Comment by eventEmitter** [comment]
ok for now
