### ISSUE TITLE
Remove bacteria

### ISSUE THREAD

**Issue by fxstr** [infect-org/frontend#73]
Difficile und non-difficile entfernen

Concerns
- [x] bacteria.json
- [ ] STATA @pascalmfrey

**Comment by eventEmitter** [comment]
@fxstr you removed them already?

remove them, re-add them when implementing the diagnosis module

**Comment by fxstr** [comment]
@eventEmitter I did. When the rda is ready, some things will have to change – we will probably not work with local JSON files any more. format and content will have to be defined.

**Comment by eventEmitter** [comment]
@fxstr since you removed them pascal still has to remove them?

**Comment by fxstr** [comment]
@eventEmitter yes, please. If the bacteria are part of the data imported from STATA, the frontend will display errors (only in the console, though – but still).
