### ISSUE TITLE
Review the updated ab class order and mappings

### ISSUE THREAD

**Issue by linaGirl** [infect-org/frontend#82]
notable updates:
- new sortorder after Aminoglycoside
- amoxi & amoxi / clavu were moved to the Penicillinase-sensitive penicilli class
- pip / taz was moved to ureido penicillin
- all classes are now displayed in english

![image](https://user-images.githubusercontent.com/603475/32376597-849cffe4-c0a5-11e7-8035-f4cc253a4f74.png)

includes changes from:
- https://github.com/infect-org/frontend/issues/76
- https://github.com/infect-org/frontend/issues/74
- https://github.com/infect-org/frontend/issues/72

**Comment by pascalmfrey** [comment]
Thanks! Can't see it in the Snippet, but it does say "Ureidopenicillin", and not "Ureido penicillin", right?
