### ISSUE TITLE
INFECT logo colour

### ISSUE THREAD

**Issue by pascalmfrey** [infect-org/frontend#86]
How does it look when the logo colour is green like the mouse-over on the filter icons? I would love to have our old INFECT green back in the logo (think of our mugs!) - unless it looks shit of course.

**Comment by sandrokneubuehl** [comment]
![screen shot 2017-11-06 at 14 27 48](https://user-images.githubusercontent.com/29794950/32443270-b0b12d16-c2fe-11e7-9662-f2c9efdfcc51.png)

**Comment by fxstr** [comment]
@sandrokneubuehl thanks a lot. mh. contrast between logo and background is very low, which reduces the logo's relevancy and the app's accessibility. i'd clearly stay with the current cleaner solution and reserve the green color for the most important ui interactions/items. 

using green (the same color as we use to set the filters) as a logo color gives the user the impression that the logo is a highly relevant link – which it clearly is not.

**Comment by fxstr** [comment]
We're probably going with the white version (for now).
