### ISSUE TITLE
update filter list to reflect new data filters

### ISSUE THREAD

**Issue by fxstr** [infect-org/frontend#98]
@sandrokneubuehl: 
- there can be 5 filter icons now
- add an indicator that indicates the current value of the sliders

![image](https://user-images.githubusercontent.com/1211144/32959551-396da668-cbc2-11e7-9053-7c12df8aa2c7.png)

**Comment by sandrokneubuehl** [comment]
das neue icon sollte noch entsprechend ausgerichtet werden (bottom)

**Comment by pascalmfrey** [comment]
This is a very well done feature! As a suggestion and further discussion point: why not rename the population filters to "data filters" and consider replacing the old population icon with the data icon? Or we could for the meantime keep the population filter icon, and use the new "statistics" icon in the future when stats like data trends, automated outbreak analysis etc. are introduced?

**Comment by fxstr** [comment]
orientation fixed: ![image](https://user-images.githubusercontent.com/1211144/33021491-4e43d052-ce02-11e7-85b1-7d555c652f05.png)

**Comment by fxstr** [comment]
Comment von @pascalmfrey in ein neues Issue überführt: #104

**Comment by fxstr** [comment]
added current value: 
![image](https://user-images.githubusercontent.com/1211144/33021813-6cc43d72-ce03-11e7-9917-0fe81d369031.png)
